name: my_template
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

#########################################################################################
#########################################################################################
#########################################################################################

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  sembast: 3.3.0
  path_provider: 2.0.11
  equatable: ^2.0.3
  auto_route: 5.0.1
  google_sign_in: ^5.0.5
  google_fonts: ^2.1.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  dartz: ^0.10.0-nullsafety.0
  flutter_riverpod: 2.0.0-dev.9
  weather_icons: ^3.0.0
  freezed_annotation: 2.1.0
  json_annotation: 4.6.0
  shared_preferences: ^2.0.7
  sizer: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  # 去除網頁URL中的“#”(hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: 0.2.0

  # Localization https://github.com/dart-lang/intl

  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.2.0

  # 網絡庫 https://github.com/flutterchina/dio
  dio: ^4.0.6

  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.3

  # Dart 常用工具類庫 https://github.com/Sky24n/common_utils
  common_utils: 2.1.0

  # Flutter 常用工具類庫 https://github.com/Sky24n/flustars
  flustars_flutter3: ^3.0.0 # flustars很久不維護，可以使用這個替代

  # Flutter 輪播圖 https://github.com/mdddj/flutter_swiper_null_safety
  flutter_swiper_null_safety_flutter3: ^2.0.0 # flutter_swiper很久不維護，可以使用這個替代

  # 啟動URL的插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.1.2

  # 圖片選擇插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.8.5+3

  # 側滑刪除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^2.0.0

  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 3.0.4

  # 處理鍵盤事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^4.0.1

  # 列表懸浮頭 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.3.0+2

  # 城市選擇列表 https://github.com/flutterchina/azlistview
  azlistview: ^2.0.0

  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3

  # 圖片緩存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.2.1

  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0

  # 狀態管理 https://github.com/rrousselGit/provider
  provider: ^6.0.3

  # 掃碼 https://github.com/juliuscanute/qr_code_scanner
  qr_code_scanner: 1.0.0

  #    git:
  #      url: https://github.com/xeinebiu/qr_code_scanner.git
  #      ref: fix_break_changes_platform
  # App Shortcuts https://github.com/flutter/plugins/tree/master/packages/quick_actions
  quick_actions: 0.6.0+11

  # 振動（支持Web） https://github.com/benjamindean/flutter_vibration
  vibration: ^1.7.4-nullsafety.0

  # 高德2D地圖插件（支持Web） https://github.com/simplezhli/flutter_2d_amap
  flutter_2d_amap:
    git:
      ref: "9e1d22ec"
      url: "https://github.com/simplezhli/flutter_2d_amap.git"
  # demo 用到的庫
  # 刮刮卡 https://github.com/vintage/scratcher
  scratcher: ^2.2.1
  # 動畫效果 https://github.com/xvrh/lottie-flutter
  lottie: ^1.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3
  transparent_image: ^2.0.0

  # Please enable Developer Mode in your system settings. Run  start ms-settings:developers
  # Flutter shared_preferences plugin util
  sp_util: 2.0.3

  # 獲取當前設備信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 4.1.2

  # 改變桌面端窗口大小(MacOS/Linux/Windows) https://github.com/mix1009/desktop_window
  desktop_window: 0.4.0
  vibration_web: ^1.6.5
  package_info: ^2.0.2
  sembast_web: ^2.0.1+1

#########################################################################################
#########################################################################################
#########################################################################################

# https://github.com/simplezhli/flutter_deer/issues/187
dependency_overrides:
  scrollable_positioned_list: ^0.3.2

#########################################################################################
#########################################################################################
#########################################################################################

dev_dependencies:
  # Widget測試
  flutter_test:
    sdk: flutter
  build_runner:

  # run the command:
  # run this once
  # flutter pub run build_runner build --delete-conflicting-outputs --output <dirname>

  # start watching for any further changes as we continue to develop.
  # flutter pub run build_runner watch --delete-conflicting-outputs --output <dirname>
  freezed: 2.1.0+1

  auto_route_generator: 5.0.2
  # to handle json easier (toJson and fromJson) for Freezed
  json_serializable: 6.3.1
  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: "^0.9.2"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints:
    ^2.0.0

    # 集成測試
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  # 黃金測試
  #  flutter_goldens:
  #    sdk: flutter
  # 單元測試
  test: ^1.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/data/
    - assets/fonts/
    - assets/launcher/
    - assets/images/
    - assets/images/home/
    - assets/images/store/
    - assets/images/state/
    - assets/images/order/
    - assets/images/order/dark/
    - assets/images/login/
    - assets/images/goods/
    - assets/images/shop/
    - assets/images/account/
    - assets/images/statistic/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# here goes all the config for flutter_gen
# watch out for the indentations
# Generation and usage
# run the command: fluttergen -c pubspec.yaml

flutter_gen:
  # by default, the generate files are in `lib/gen/`
  # you can set other directories like `lib/src/gen` using [output]
  output:
    lib/core/flutter_gen

    # if you use some linter that is line-of-code-sensitive
    # you can satisfy the lines it demands with [lineLength]
    # the default value is 80
  lineLength: 90

  # integrations are optional if you use another 3rd party
  # package, like [flutter_svg] to use .svg files like we
  # do with fonts and images
  #
  # it's important to have your integrations as project dependencies
  integrations:
    flutter_svg: true

    # you can also add color files in XML format
    # if you're reusing from an android project
